#!/bin/bash

has_yazi=false

set -e

base="$(pwd)"
yazi="$HOME/.config/yazi/plugins"

[ -d "$yazi" ] && command -v yazi >/dev/null && has_yazi=true || true
if $has_yazi ; then
    ln -s "$base/tag.yazi" "$yazi" 2>/dev/null || true
    file="$yazi/keymap.toml"
    grep -e 'on\s*=\s*\[\s*"\["\s*\]' "$file" >/dev/null ||
        echo -e "[[manager.prepend_keymap]]\non = [ \"[\" ]\nrun = \"plugin tag\"\ndesc = \"add tags\"" >> "$file"
fi

mkdir -p bin && cp -f tag bin/
PATH="$PATH:$base/bin"
mkdir -p testing && cd testing
mkdir -p all cute image video audio cool interesting mountain landscape
touch all/{lol.jpg,cool.png,something.png,yes.mp4,what.mp3,ahem.png}
$has_yazi && yazi all
tag -h
